// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBepeAyNHMWAy4vTCF3TYN9XebPybT9fE',
    appId: '1:1075739251715:web:3897fd766297128a082a36',
    messagingSenderId: '1075739251715',
    projectId: 'connected-cc617',
    authDomain: 'connected-cc617.firebaseapp.com',
    storageBucket: 'connected-cc617.appspot.com',
    measurementId: 'G-7HKQGKE2GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXioNfHE3Zglax03UNYgE-viAOJVXKv88',
    appId: '1:1075739251715:android:3cc7c1606cd5a021082a36',
    messagingSenderId: '1075739251715',
    projectId: 'connected-cc617',
    storageBucket: 'connected-cc617.appspot.com',
  );
}
